name: Deploy to Apache Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libssl-dev

    - name: Build application
      run: |
        make build

    - name: Deploy application
      uses: appleboy/scp-action@master
      with:
        host: jaredvillanueva.com
        username: jared
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/"
        target: "/var/www/jaredvillanueva.com/public_html/"

    - name: Restart Apache
      run: sudo service apache2 restart

